name: Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
            node-version: 12
      - uses: egordm/gha-yarn-node-cache@v1
      - name: Install and Build
        run: |
          npm install

      - name: Buile Project
        run: |
          npm run build
          rm -rf ./node_modules
      - name: OSS Upload Tool
        uses: youmengme/oss-upload-tool@v1.0.2
        with:
          accessKeyId: ${{ secrets.OSS_ID }}
          accessKeySecret: ${{ secrets.OSS_SECRET }}
          bucket: ${{ secrets.OSS_BUCKET }}
          region: ${{ secrets.OSS_REGION }}
          assetPath:: ./.nuxt/dist/client/
          targetPath: /static/
      - name: Copy File To Service
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USER_NAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          overwrite: true
          source: ".nuxt,ecosystem.config.js,package.json"
          target: "/www/wwwroot/www.youmeng.me/client"

      - name: Install and Start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /www/wwwroot/www.youmeng.me/client
            yarn
            npm run deploy
